### ISSUE TITLE
Why use dep when vendoring is build into Go?

### ISSUE THREAD

**Issue by erikdubbelboer** [kevburnsjr/microcache#6]
Why not use the standard `go.mod` and `go.sum` that everyone is using these days? `dep` is old and deprecated.

You should probably also tag a proper semver version such as `v1.0.0`.

**Comment by kevburnsjr** [comment]
Because I run `dep init` it just works.

I know `go.mod` is the new defacto I just haven't ever worked on a repository that uses it.

**Comment by kevburnsjr** [comment]
#7 open to replace dep with mod

**Comment by kevburnsjr** [comment]
Dep replaced with mod.
https://github.com/kevburnsjr/microcache/pull/7

v1.0.0 tagged.
https://github.com/kevburnsjr/microcache/releases/tag/v1.0.0
